language: cpp

sudo: required

services:
  - docker

compiler:
  - clang

before_install:
  - docker pull tkzdockerid/corct-testenv:clang-11-0-A

script:
  - docker run -it tkzdockerid/corct-testenv:clang-11-0-A /bin/bash test_coarct.sh $TRAVIS_BRANCH
