language: cpp

sudo: required

services:
  - docker

compiler:
  - clang

before_install:
  - docker pull tkzdockerid/corct-testenv:clang-10-0-C

script:
  - docker run -it tkzdockerid/corct-testenv:clang-10-0-C /bin/bash test_coarct.sh $TRAVIS_BRANCH
